[package]
name = "blackferrari2/blackferraribox"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "HITBOXES!!!"

exclude = [
    "aftman.toml", 
    "README.md",
    "test.project.json"
]

[dependencies]
Signal = "sleitnick/signal@2.0.1"